### ISSUE TITLE
Лучше называть в формате adidas-discount

### ISSUE THREAD

**Issue by coursar** [ElenaVeselovskaya/adidas-discount#2]

**Comment by ElenaVeselovskaya** [comment]
@coursar, где поменять название?

**Comment by coursar** [comment]
![Screenshot from 2019-09-18 18-45-42](https://user-images.githubusercontent.com/3601892/65163931-8ecde400-da44-11e9-9c9d-269b37440ee9.png)

После этого надо будет сделать:
```
git remote remove origin
git remote add origin <ссылка на новый репо>
```
